name: yuvraj

on: push


jobs:
  yuvraj:
    name: workflow base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Yuvraj
        uses: github/yuvraj@v3
        env:
          DEFAULT BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
